"use client";

import { useState } from "react";
import PageHeader from "@/components/PageHeader";
import { Calendar, Clock, AlertTriangle, CheckCircle2, Zap, Filter } from "lucide-react";

// Simple date formatter to avoid hydration issues
const formatDate = (dateString: string) => {
  const date = new Date(dateString);
  const month = date.toLocaleString('en-US', { month: 'short', timeZone: 'UTC' });
  const day = date.getUTCDate();
  const year = date.getUTCFullYear();
  return `${month} ${day}, ${year}`;
};

interface ComplianceEvent {
  id: string;
  title: string;
  type: "deadline" | "meeting" | "audit" | "submission" | "review";
  date: string;
  status: "upcoming" | "overdue" | "completed";
  priority: "critical" | "high" | "medium" | "low";
  source: "rbi-requirement" | "internal-policy" | "board-decision" | "auto-generated";
  description: string;
  assignedTo: string;
  relatedRequirement?: string;
  autoGenerated: boolean;
}

const mockEvents: ComplianceEvent[] = [
  {
    id: "1",
    title: "Capital Adequacy Ratio - Increase to 18%",
    type: "deadline",
    date: "2024-04-01",
    status: "upcoming",
    priority: "critical",
    source: "rbi-requirement",
    description: "Comply with new CAR requirement of 18% for Upper Layer NBFCs",
    assignedTo: "CFO",
    relatedRequirement: "RBI/DoR/2024/15 - Scale Based Regulation Amendment",
    autoGenerated: true
  },
  {
    id: "2",
    title: "Risk Committee Meeting (Monthly)",
    type: "meeting",
    date: "2024-02-15",
    status: "upcoming",
    priority: "high",
    source: "auto-generated",
    description: "Monthly Risk Committee meeting as per new RBI requirement",
    assignedTo: "Company Secretary",
    relatedRequirement: "RBI Circular - Board Meeting Frequency",
    autoGenerated: true
  },
  {
    id: "3",
    title: "Fraud Reporting Timeline Update",
    type: "deadline",
    date: "2024-02-01",
    status: "upcoming",
    priority: "high",
    source: "rbi-requirement",
    description: "Update Fraud Risk Management Policy to reflect 72-hour reporting timeline",
    assignedTo: "Risk Manager",
    relatedRequirement: "RBI/DoR/2024/12 - Fraud Reporting Timeline Update",
    autoGenerated: true
  },
  {
    id: "4",
    title: "Quarterly Board Meeting",
    type: "meeting",
    date: "2024-01-30",
    status: "upcoming",
    priority: "medium",
    source: "internal-policy",
    description: "Regular quarterly board meeting",
    assignedTo: "Company Secretary",
    autoGenerated: false
  },
  {
    id: "5",
    title: "Annual Compliance Audit",
    type: "audit",
    date: "2024-03-15",
    status: "upcoming",
    priority: "critical",
    source: "internal-policy",
    description: "Annual external compliance audit",
    assignedTo: "Compliance Head",
    autoGenerated: false
  }
];

export default function ComplianceCalendarPage() {
  const [filter, setFilter] = useState<"all" | "auto-generated">("all");
  const [viewMode, setViewMode] = useState<"list" | "calendar">("list");

  const filteredEvents = mockEvents.filter(event => 
    filter === "all" || (filter === "auto-generated" && event.autoGenerated)
  );

  const getTypeColor = (type: string) => {
    switch (type) {
      case "deadline": return "bg-red-100 text-red-900 border-red-300";
      case "meeting": return "bg-blue-100 text-blue-900 border-blue-300";
      case "audit": return "bg-purple-100 text-purple-900 border-purple-300";
      case "submission": return "bg-green-100 text-green-900 border-green-300";
      case "review": return "bg-yellow-100 text-yellow-900 border-yellow-300";
      default: return "bg-gray-100 text-gray-900 border-gray-300";
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "critical": return "text-red-800";
      case "high": return "text-orange-800";
      case "medium": return "text-yellow-800";
      case "low": return "text-blue-800";
      default: return "text-gray-800";
    }
  };

  const getDaysUntil = (date: string) => {
    const days = Math.ceil((new Date(date).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24));
    return days;
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Compliance Calendar"
        description="Auto-updated deadlines based on regulatory changes"
      />

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-700">Upcoming Deadlines</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">
                {mockEvents.filter(e => e.type === "deadline" && e.status === "upcoming").length}
              </p>
            </div>
            <div className="h-12 w-12 bg-red-100 rounded-lg flex items-center justify-center">
              <AlertTriangle className="h-6 w-6 text-red-600" />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-700">This Month</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">
                {mockEvents.filter(e => new Date(e.date).getMonth() === new Date().getMonth()).length}
              </p>
            </div>
            <div className="h-12 w-12 bg-blue-100 rounded-lg flex items-center justify-center">
              <Calendar className="h-6 w-6 text-blue-600" />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-700">Auto-Generated</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">
                {mockEvents.filter(e => e.autoGenerated).length}
              </p>
            </div>
            <div className="h-12 w-12 bg-purple-100 rounded-lg flex items-center justify-center">
              <Zap className="h-6 w-6 text-purple-600" />
            </div>
          </div>
          <p className="text-xs font-medium text-gray-600 mt-2">From RBI updates</p>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-700">Completed</p>
              <p className="text-3xl font-bold text-green-600 mt-1">
                {mockEvents.filter(e => e.status === "completed").length}
              </p>
            </div>
            <div className="h-12 w-12 bg-green-100 rounded-lg flex items-center justify-center">
              <CheckCircle2 className="h-6 w-6 text-green-600" />
            </div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex gap-2">
          <button
            onClick={() => setFilter("all")}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              filter === "all"
                ? "bg-blue-600 text-white"
                : "bg-white text-gray-700 border border-gray-300 hover:bg-gray-50"
            }`}
          >
            All Events
          </button>
          <button
            onClick={() => setFilter("auto-generated")}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 ${
              filter === "auto-generated"
                ? "bg-blue-600 text-white"
                : "bg-white text-gray-700 border border-gray-300 hover:bg-gray-50"
            }`}
          >
            <Zap className="h-4 w-4" />
            Auto-Generated Only
          </button>
        </div>
      </div>

      {/* Events List */}
      <div className="space-y-4">
        {filteredEvents.map((event) => {
          const daysUntil = getDaysUntil(event.date);

          return (
            <div
              key={event.id}
              className="bg-white rounded-lg border border-gray-200 p-6 hover:shadow-md transition-shadow"
            >
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <span className={`px-3 py-1 rounded-full text-xs font-semibold border ${getTypeColor(event.type)}`}>
                      {event.type.toUpperCase().replace("-", " ")}
                    </span>
                    {event.autoGenerated && (
                      <span className="flex items-center gap-1 px-2 py-1 bg-purple-100 text-purple-900 rounded text-xs font-semibold border border-purple-200">
                        <Zap className="h-3 w-3" />
                        Auto-Generated
                      </span>
                    )}
                    <span className={`font-bold ${getPriorityColor(event.priority)}`}>
                      {event.priority.toUpperCase()}
                    </span>
                  </div>

                  <h3 className="text-lg font-semibold text-gray-900 mb-2">{event.title}</h3>
                  <p className="text-sm text-gray-800 mb-3">{event.description}</p>

                  <div className="flex items-center gap-6 text-sm text-gray-700 font-medium">
                    <span className="flex items-center gap-1">
                      <Calendar className="h-4 w-4" />
                      {formatDate(event.date)}
                    </span>
                    <span className="flex items-center gap-1">
                      <Clock className="h-4 w-4" />
                      {daysUntil > 0 ? `${daysUntil} days away` : daysUntil === 0 ? "Today" : `${Math.abs(daysUntil)} days overdue`}
                    </span>
                    <span>Assigned to: <strong className="text-gray-900">{event.assignedTo}</strong></span>
                  </div>

                  {event.relatedRequirement && (
                    <div className="mt-3 pt-3 border-t border-gray-100">
                      <div className="text-xs font-semibold text-gray-700 mb-1">Related Requirement:</div>
                      <div className="text-sm text-blue-700 font-semibold">{event.relatedRequirement}</div>
                    </div>
                  )}
                </div>

                <div className="ml-6 flex flex-col gap-2">
                  <button className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors">
                    View Details
                  </button>
                  <button className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors">
                    Mark Complete
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}


